CI Workflows improvements (#14)

diff --git a/.github/workflows/cmake-macos-12.yml b/.github/workflows/cmake-macos-12.yml
--- a/.github/workflows/cmake-macos-12.yml
+++ b/.github/workflows/cmake-macos-12.yml
@@ -1,10 +1,9 @@
-name: Build MacOS 12
+name: Build MacOS 12 Monterey
 
 on:
   push:
     branches:
        - main
-       - Improve-CI
   pull_request:
     branches: [ main ]
 
@@ -30,8 +29,8 @@ jobs:
            rm /usr/local/bin/pydoc3
            rm /usr/local/bin/python3
            rm /usr/local/bin/python3-config
-           brew upgrade
            brew install qt@5 cmake extra-cmake-modules stk
+           ls $(brew --prefix stk)
            
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
@@ -39,6 +38,7 @@ jobs:
       run: |
            cmake -B ${{github.workspace}}/build \
                  -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
+                 -DSTK_DIR=$(brew --prefix stk) \
                  -DCMAKE_INSTALL_PREFIX=tuningTrainer.app \
                  -DCMAKE_OSX_ARCHITECTURES="x86_64" \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
@@ -54,9 +54,11 @@ jobs:
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           #make install
+           make install
            $(brew --prefix qt5)/bin/macdeployqt tuningTrainer.app
-           codesign -dv --verbose=4 qbrainwave.app || echo "Codesign FAILED"
+           export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/usr/bin/codesign_allocate"
+           codesign --force --sign "Developer ID Application: donarturo11" tuningTrainer.app || echo "Create sign FAILED"
+           codesign -dv --verbose=4 tuningTrainer.app || echo "Codesign FAILED"
            
     - name: Prepare Artifact
       run: |
