Improve CI

diff --git a/.github/workflows/cmake-macos-12.yml b/.github/workflows/cmake-macos-12.yml
--- a/.github/workflows/cmake-macos-12.yml
+++ b/.github/workflows/cmake-macos-12.yml
@@ -31,6 +31,7 @@ jobs:
            rm /usr/local/bin/python3
            rm /usr/local/bin/python3-config
            brew install qt@5 cmake extra-cmake-modules stk
+           ls $(brew --prefix stk)
            
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
@@ -54,9 +55,9 @@ jobs:
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           #make install
+           make install
            $(brew --prefix qt5)/bin/macdeployqt tuningTrainer.app
-           codesign -dv --verbose=4 qbrainwave.app || echo "Codesign FAILED"
+           codesign -dv --verbose=4 tuningTrainer.app || echo "Codesign FAILED"
            
     - name: Prepare Artifact
       run: |
