CI Workflows improvements (#14)

diff --git a/.github/workflows/cmake-macos-11.yml b/.github/workflows/cmake-macos-11.yml
--- a/.github/workflows/cmake-macos-11.yml
+++ b/.github/workflows/cmake-macos-11.yml
@@ -1,10 +1,9 @@
-name: Build MacOS 11
+name: Build MacOS 11 BigSur
 
 on:
   push:
     branches:
        - main
-       - Improve-CI
   pull_request:
     branches: [ main ]
 
@@ -25,13 +24,23 @@ jobs:
     - name: Install dependencies
       run: |
            brew update
+           rm /usr/local/bin/2to3
+           rm /usr/local/bin/idle3
+           rm /usr/local/bin/pydoc3
+           rm /usr/local/bin/python3
+           rm /usr/local/bin/python3-config
            brew install qt@5 cmake extra-cmake-modules stk
+           ls $(brew --prefix stk)
            
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: |
            cmake -B ${{github.workspace}}/build \
+                 -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
+                 -DSTK_DIR=$(brew --prefix stk) \
+                 -DCMAKE_INSTALL_PREFIX=tuningTrainer.app \
+                 -DCMAKE_OSX_ARCHITECTURES="x86_64" \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
 
     - name: Build
@@ -46,7 +55,10 @@ jobs:
       run: |
            cd ${{github.workspace}}/build
            make install
-           /usr/local/Cellar/qt@5/5.15.3/bin/macdeployqt tuningTrainer.app
+           $(brew --prefix qt5)/bin/macdeployqt tuningTrainer.app
+           export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/usr/bin/codesign_allocate"
+           codesign --force --sign "Developer ID Application: donarturo11" tuningTrainer.app || echo "Create sign FAILED"
+           codesign -dv --verbose=4 tuningTrainer.app || echo "Codesign FAILED"
            
     - name: Prepare Artifact
       run: |
@@ -60,6 +72,6 @@ jobs:
     - name: Upload tuningTrainer-mac
       uses: actions/upload-artifact@v3.0.0
       with:
-        name: tuningTrainer-macos-11
+        name: tuningTrainer-macos-12
         path: ${{github.workspace}}/build/artifacts
         
