CI MacOS: rewrite action

diff --git a/.github/workflows/cmake-macos-12.yml b/.github/workflows/cmake-macos-12.yml
--- a/.github/workflows/cmake-macos-12.yml
+++ b/.github/workflows/cmake-macos-12.yml
@@ -25,6 +25,12 @@ jobs:
     - name: Install dependencies
       run: |
            brew update
+           rm /usr/local/bin/2to3
+           rm /usr/local/bin/idle3
+           rm /usr/local/bin/pydoc3
+           rm /usr/local/bin/python3
+           rm /usr/local/bin/python3-config
+           brew upgrade
            brew install qt@5 cmake extra-cmake-modules stk
            
     - name: Configure CMake
@@ -32,6 +38,9 @@ jobs:
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: |
            cmake -B ${{github.workspace}}/build \
+                 -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
+                 -DCMAKE_INSTALL_PREFIX=tuningTrainer.app \
+                 -DCMAKE_OSX_ARCHITECTURES="x86_64" \
                  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
 
     - name: Build
@@ -45,8 +54,9 @@ jobs:
     - name: Build Package
       run: |
            cd ${{github.workspace}}/build
-           make install
-           /usr/local/Cellar/qt@5/5.15.3/bin/macdeployqt tuningTrainer.app
+           #make install
+           $(brew --prefix qt5)/bin/macdeployqt tuningTrainer.app
+           codesign -dv --verbose=4 qbrainwave.app || echo "Codesign FAILED"
            
     - name: Prepare Artifact
       run: |
