Fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -194,9 +194,10 @@ jobs:
           cp *.dmg $DMGDIR
           echo "DMGDIR=${DMGDIR}" >> $GITHUB_ENV
           
-    - name: Staple packages (macOS)
+    - name: Verify (macOS)
       if: ${{runner.os == 'macOS'}}
       run: |
+          find . -name "*.app" -exec codesign -s "donarturo11.github.io" -f --timestamp --preserve-metadata --generate-entitlement-der {} || echo "Fail" \;
           find . -name "*.dmg" -exec xcrun stapler staple {} \;
           find . -name "*.app" -exec xcrun stapler staple {} \;
           
