Add MacOS certificates
Fix certificates

Fix certificates

Fix certificates

Fix certificates

Fix

Fix

Fix

Fix

Fix

Fix

Fix

Fix

Fix

Fix

Fix

fix

Debug cpack

fix

fix

fix

fix

fix

fix

fix

fix

Add embedding icon

Revert "Add embedding icon"

This reverts commit a88a42fbc11e763ad3773c3d71237013e1ffa8e8.

Rename icons

Update CMakeLists.txt

fix

fix

Improve MacOS building

Improve syntax

fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
     strategy:
       matrix:
        include:
-        - { os: windows-latest, flags: "", shell: 'msys2 {0}', deps-prefix: "/opt/deps", aqt-os: "windows", aqt-arch: "win64_mingw", aqt-prefix: "/opt/Qt", aqt-module: "mingw_64" }
+        #- { os: windows-latest, flags: "", shell: 'msys2 {0}', deps-prefix: "/opt/deps", aqt-os: "windows", aqt-arch: "win64_mingw", aqt-prefix: "/opt/Qt", aqt-module: "mingw_64" }
         #- { os: ubuntu-latest, flags: "", shell: 'bash', deps-prefix: "/home/runner/deps", aqt-os: "linux", aqt-arch: "gcc_64", aqt-prefix: "/home/runner/Qt", aqt-module: "gcc_64"}
         - { os: macos-latest, flags: "-DCMAKE_OSX_ARCHITECTURES=\"x86_64;arm64\"", shell: 'bash', deps-prefix: "/Users/runner/deps", aqt-os: "mac", aqt-arch: "", aqt-prefix: "/Users/runner/Qt", aqt-module: "macos" }
     runs-on: ${{matrix.os}}
@@ -93,6 +93,26 @@ jobs:
 
     - name: Checkout Repo
       uses: actions/checkout@v2
+
+# see: https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development    
+#    - name: Install the Apple certificate and provisioning profile
+#      if: ${{runner.os == 'macOS'}}
+#      run: |
+#          PEM_CERT=$RUNNER_TEMP/donarturo11.pem
+#          PEM_KEY=$RUNNER_TEMP/donarturo11.key
+#          P12_CERT=$RUNNER_TEMP/donarturo11.p12
+#          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+#          PASSWORD=passwd
+#          NAME="Developer ID Application: org.donarturo11.${{env.pkgname}}.com"
+#          openssl genrsa -des3 -passout pass:$PASSWORD -out $PEM_KEY 2048 || echo "Fail genrsa"
+#          openssl req -subj '/C=PL/CN=org.donarturo11.tuningtrainer.com/O=donarturo11' \
+#                      -key $PEM_KEY -nodes -days 365 -x509 \
+#                      -out $PEM_CERT \
+#                      -passin "pass:${PASSWORD}" -passout "pass:${PASSWORD}" || echo "Fail req"
+#          #openssl pkcs12 -inkey $PEM_KEY -in $PEM_CERT -export -out $P12_CERT -password "pass:${PASSWORD}" -caname "${NAME}" -name "${NAME}"
+#          security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" $PEM_CERT || echo "Fail add trusted cert"
+#          
+##
     
     - name: Prepare workdir (UNIX)
       if: ${{runner.os != 'Windows'}}
@@ -141,7 +161,7 @@ jobs:
     - name: Install
       run: |
            cmake --install ${{env.WORKDIR}}/build --prefix ${{ env.INSTALL_PREFIX }}
-
+    
     - name: macdeployqt
       if: ${{runner.os == 'macOS'}}
       run: |
@@ -154,9 +174,23 @@ jobs:
            cp -v ${{env.DEPSPATH}}/bin/*.dll ${{env.APPDIR}}/
            ${{matrix.aqt-prefix}}/${{env.qt-version}}/${{matrix.aqt-module}}/bin/windeployqt.exe ${{env.APPDIR}}/
 
+    - name: Add missing audio libraries
+      if: ${{runner.os == 'macOS'}}
+      run: |
+           find ${{env.DEPSPATH}} -name "*.dylib" -exec cp {} ${{env.APPDIR}}/Contents/Frameworks \;
+
     - name: CPack
       run: |
            cpack --config ${{env.WORKDIR}}/build/CPackConfig.cmake
+    
+    - name: Upload DMG
+      if: ${{runner.os == 'macOS'}}
+      run: |
+          export DMGDIR=${{env.pkgname}}-DMG
+          mkdir $DMGDIR
+          cp *.dmg $DMGDIR
+          echo "DMGDIR=${DMGDIR}" >> $GITHUB_ENV
+          
 
     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v3
@@ -169,9 +203,16 @@ jobs:
     - name: Upload All Binaries
       uses: actions/upload-artifact@v2
       with:
-        name: build-${{runner.os}}
+        name: ${{env.pkgname}}-${{runner.os}}
         path: ${{github.workspace}}/${{env.pkgname}}-${{runner.os}}
-    
+        
+    - name: Upload DMG
+      if: ${{runner.os == 'macOS'}}
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{env.pkgname}}-${{runner.os}}-DMG
+        path: ${{github.workspace}}/${{env.DMGDIR}}
+        
     - name: Print variables
       run: |
           echo "::notice:: github.event_name = ${{ github.event_name }}"
